[team_commons]
database_port = "5378"
database_name = "seedpro"
tables = ['t1', 't2']

[dev]
database_host = "dev-db.host"
database_password = "dev_secret"

[stg]
database_host = "stg-db.host"
database_password = "stg_secret"
s3_bucket = "sysco-seed-eu-np-external-inbound"
s3_path = "PGM/FRA/Hierarchy - ID mapping/"

[prod]
database_host = "prod-db.host"
database_password = "prod_secret"
