name: Upload YAML to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest  # or a lighter version like ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1

      - name: Upload YAML files to S3
        run: |
          aws s3 sync data_checks/ s3://sysco-seed-eu-np-external-inbound/data_checks/ --exact-timestamps --delete